import 'package:neztmate_backend/features/units/models/unit_model.dart';

class LeaseModel {
  final String id;
  final String applicationId;
  final String unitId;
  final String tenantId;
  final String landownerId;
  final String propertyId;
  final String? managerId;

  final DateTime startDate;
  final DateTime endDate;
  final DateTime? nextDueDate;

  final double yearlyRent;
  final int? rentTermInMonths;
  final List<UnitFee>? fees;

  final String
  status; // 'Pending Signature', 'Pending Payment', 'Inactive', 'Active', 'Expired', 'Terminated', 'Renew', 'Cancelled'

  // Document Handling
  final String? generatedLeasePdfUrl; // Auto-generated by system
  final String? customLeasePdfUrl; // Uploaded by landowner
  final String? signedAgreementPdfUrl; // Final signed document by tenant

  final bool isCustomLease; // true if landowner uploaded their own
  final DateTime? signedAt;
  final String? signedBy; // Tenant ID who signed

  final String? termsNotes;

  final String? terminationReason;
  final DateTime? terminatedAt;
  final String? terminatedBy;

  final DateTime createdAt;
  final DateTime updatedAt;

  final bool isRenewed;
  final String? previousLeaseId;
  final String? renewalReason;

  LeaseModel({
    required this.id,
    required this.applicationId,
    required this.unitId,
    required this.tenantId,
    required this.landownerId,
    required this.propertyId,
    this.managerId,
    required this.startDate,
    required this.endDate,
    this.nextDueDate,
    required this.yearlyRent,
    this.fees,
    this.rentTermInMonths,
    this.status = 'Pending Signature',
    this.generatedLeasePdfUrl,
    this.customLeasePdfUrl,
    this.signedAgreementPdfUrl,
    this.isCustomLease = false,
    this.signedAt,
    this.signedBy,
    this.termsNotes,
    required this.createdAt,
    required this.updatedAt,
    this.terminationReason,
    this.terminatedAt,
    this.terminatedBy,

    this.isRenewed = false,
    this.previousLeaseId,
    this.renewalReason,
  });

  factory LeaseModel.fromMap(Map<String, dynamic> map) {
    return LeaseModel(
      id: map['id'] as String,
      applicationId: map['applicationId'] as String,
      unitId: map['unitId'] as String,
      tenantId: map['tenantId'] as String,
      landownerId: map['landownerId'] as String,
      propertyId: map['propertyId'] as String,
      managerId: map['managerId'] as String?,
      startDate: DateTime.parse(map['startDate'] as String),
      endDate: DateTime.parse(map['endDate'] as String),
      nextDueDate: map['nextDueDate'] != null ? DateTime.parse(map['nextDueDate'] as String) : null,
      yearlyRent: (map['yearlyRent'] as num).toDouble(),
      rentTermInMonths: (map['rentTermInMonths'] as num?)?.toInt(),
      fees: (map['fees'] as List?)?.map((e) => UnitFee.fromMap(e)).toList(),

      status: map['status'] as String? ?? 'Pending Signature',
      generatedLeasePdfUrl: map['generatedLeasePdfUrl'] as String?,
      customLeasePdfUrl: map['customLeasePdfUrl'] as String?,
      signedAgreementPdfUrl: map['signedAgreementPdfUrl'] as String?,
      isCustomLease: map['isCustomLease'] as bool? ?? false,
      signedAt: map['signedAt'] != null ? DateTime.parse(map['signedAt'] as String) : null,
      signedBy: map['signedBy'] as String?,
      termsNotes: map['termsNotes'] as String?,
      createdAt: DateTime.parse(map['createdAt'] as String),
      updatedAt: DateTime.parse(map['updatedAt'] as String),
      terminationReason: map['terminationReason'] as String?,
      terminatedAt: map['terminatedAt'] != null ? DateTime.parse(map['terminatedAt'] as String) : null,
      terminatedBy: map['terminatedBy'] as String?,

      isRenewed: map['isRenewed'] as bool? ?? false,
      previousLeaseId: map['previousLeaseId'] as String?,
      renewalReason: map['renewalReason'] as String?,
    );
  }

  Map<String, dynamic> toMap() => {
    'id': id,
    'applicationId': applicationId,
    'unitId': unitId,
    'tenantId': tenantId,
    'landownerId': landownerId,
    'propertyId': propertyId,
    'managerId': managerId,
    'startDate': startDate.toIso8601String(),
    'endDate': endDate.toIso8601String(),
    'nextDueDate': nextDueDate?.toIso8601String(),
    'yearlyRent': yearlyRent,
    'fees': fees?.map((e) => e.toMap()).toList(),

    'rentTermInMonths': rentTermInMonths,
    'status': status,
    'generatedLeasePdfUrl': generatedLeasePdfUrl,
    'customLeasePdfUrl': customLeasePdfUrl,
    'signedAgreementPdfUrl': signedAgreementPdfUrl,
    'isCustomLease': isCustomLease,
    'signedAt': signedAt?.toIso8601String(),
    'signedBy': signedBy,
    'termsNotes': termsNotes,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'terminationReason': terminationReason,
    'terminatedAt': terminatedAt?.toIso8601String(),
    'terminatedBy': terminatedBy,

    'isRenewed': isRenewed,
    'previousLeaseId': previousLeaseId,
    'renewalReason': renewalReason,
  };

  LeaseModel copyWith({
    String? id,
    String? applicationId,
    String? unitId,
    String? tenantId,
    String? landownerId,
    String? propertyId,
    String? managerId,
    DateTime? startDate,
    DateTime? endDate,
    DateTime? nextDueDate,
    double? yearlyRent,
    int? rentTermInMonths,
    String? status,
    String? generatedLeasePdfUrl,
    String? customLeasePdfUrl,
    String? signedAgreementPdfUrl,
    String? terminationReason,
    List<UnitFee>? fees,
    DateTime? terminatedAt,
    String? terminatedBy,
    bool? isCustomLease,
    DateTime? signedAt,
    String? signedBy,
    String? termsNotes,
    DateTime? createdAt,
    DateTime? updatedAt,

    bool? isRenewed,
    String? previousLeaseId,
    String? renewalReason,
  }) {
    return LeaseModel(
      id: id ?? this.id,
      applicationId: applicationId ?? this.applicationId,
      unitId: unitId ?? this.unitId,
      tenantId: tenantId ?? this.tenantId,
      landownerId: landownerId ?? this.landownerId,
      managerId: managerId ?? this.managerId,
      propertyId: propertyId ?? this.propertyId,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      nextDueDate: nextDueDate ?? this.nextDueDate,
      yearlyRent: yearlyRent ?? this.yearlyRent,
      fees: fees ?? this.fees,
      rentTermInMonths: rentTermInMonths ?? this.rentTermInMonths,
      status: status ?? this.status,
      generatedLeasePdfUrl: generatedLeasePdfUrl ?? this.generatedLeasePdfUrl,
      customLeasePdfUrl: customLeasePdfUrl ?? this.customLeasePdfUrl,
      signedAgreementPdfUrl: signedAgreementPdfUrl ?? this.signedAgreementPdfUrl,
      isCustomLease: isCustomLease ?? this.isCustomLease,
      signedAt: signedAt ?? this.signedAt,
      signedBy: signedBy ?? this.signedBy,
      termsNotes: termsNotes ?? this.termsNotes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      terminationReason: terminationReason ?? this.terminationReason,
      terminatedAt: terminatedAt ?? this.terminatedAt,
      terminatedBy: terminatedBy ?? this.terminatedBy,
      isRenewed: isRenewed ?? this.isRenewed,
      previousLeaseId: previousLeaseId ?? this.previousLeaseId,
      renewalReason: renewalReason ?? this.renewalReason,
    );
  }
}
