import 'package:neztmate_backend/features/units/models/unit_model.dart';

class LeaseModel {
  final String id;
  final String applicationId;
  final String unitId;
  final String tenantId;
  final String landownerId;
  final String propertyId;
  final String? managerId;

  final DateTime startDate;
  final DateTime endDate;
  final DateTime? nextDueDate;

  final double monthlyRent;
  final int? durationMonths;
  final double? monthlyRentEquivalent;

  final List<UnitFee>? fees;

  final String
  status; // 'Pending Signature', 'Pending Payment', 'Inactive', 'Active', 'Expired', 'Terminated', 'Renew', 'Cancelled'

  // Document Handling
  final String? generatedLeasePdfUrl; // Auto-generated by system
  final String? customLeasePdfUrl; // Uploaded by landowner
  final String? signedAgreementPdfUrl; // Final signed document by tenant

  final bool isCustomLease; // true if landowner uploaded their own
  final DateTime? signedAt;
  final String? signedBy; // Tenant ID who signed

  final String? termsNotes;

  final String? terminationReason;
  final DateTime? terminatedAt;
  final DateTime? renewalRequestedAt;
  final DateTime? terminationRequestedAt;
  final String? terminatedBy;

  final String? transferToTenantId; // For lease transfer
  final String? transferStatus; // Pending, Approved, Rejected
  final DateTime? transferRequestedAt;
  final DateTime? paymentConfirmedAt;
  final DateTime? renewedAt;

  final DateTime createdAt;
  final DateTime updatedAt;

  final bool isRenewed;
  final String? previousLeaseId;
  final String? renewalReason;

  final DateTime? transferApprovedAt;
  final String? transferApprovedBy;

  LeaseModel({
    required this.id,
    required this.applicationId,
    required this.unitId,
    required this.tenantId,
    required this.landownerId,
    required this.propertyId,
    this.managerId,
    required this.startDate,
    required this.endDate,
    this.monthlyRentEquivalent,
    this.nextDueDate,
    required this.monthlyRent,
    this.fees,
    this.durationMonths,
    this.status = 'Pending Signature',
    this.generatedLeasePdfUrl,
    this.customLeasePdfUrl,
    this.signedAgreementPdfUrl,
    this.isCustomLease = false,
    this.signedAt,
    this.signedBy,
    this.termsNotes,
    required this.createdAt,
    required this.updatedAt,
    this.terminationReason,
    this.terminatedAt,
    this.renewalRequestedAt,
    this.terminationRequestedAt,
    this.transferRequestedAt,
    this.paymentConfirmedAt,
    this.renewedAt,
    this.terminatedBy,

    this.transferToTenantId,
    this.transferStatus,

    this.isRenewed = false,
    this.previousLeaseId,
    this.renewalReason,

    this.transferApprovedAt,
    this.transferApprovedBy,
  });

  factory LeaseModel.fromMap(Map<String, dynamic> map) {
    return LeaseModel(
      id: map['id'] as String,
      applicationId: map['applicationId'] as String,
      unitId: map['unitId'] as String,
      tenantId: map['tenantId'] as String,
      landownerId: map['landownerId'] as String,
      propertyId: map['propertyId'] as String,
      managerId: map['managerId'] as String?,
      monthlyRentEquivalent: map['monthlyRentEquivalent'] as double?,
      startDate: DateTime.parse(map['startDate'] as String),
      endDate: DateTime.parse(map['endDate'] as String),
      nextDueDate: map['nextDueDate'] != null ? DateTime.parse(map['nextDueDate'] as String) : null,
      monthlyRent: (map['monthlyRent'] as num).toDouble(),
      durationMonths: (map['durationMonths'] as num?)?.toInt(),
      fees: (map['fees'] as List?)?.map((e) => UnitFee.fromMap(e)).toList(),

      status: map['status'] as String? ?? 'Pending Signature',
      generatedLeasePdfUrl: map['generatedLeasePdfUrl'] as String?,
      customLeasePdfUrl: map['customLeasePdfUrl'] as String?,
      signedAgreementPdfUrl: map['signedAgreementPdfUrl'] as String?,
      isCustomLease: map['isCustomLease'] as bool? ?? false,
      signedAt: map['signedAt'] != null ? DateTime.parse(map['signedAt'] as String) : null,
      signedBy: map['signedBy'] as String?,
      termsNotes: map['termsNotes'] as String?,
      createdAt: DateTime.parse(map['createdAt'] as String),
      updatedAt: DateTime.parse(map['updatedAt'] as String),
      terminationReason: map['terminationReason'] as String?,
      terminatedAt: map['terminatedAt'] != null ? DateTime.parse(map['terminatedAt'] as String) : null,
      renewalRequestedAt: map['renewalRequestedAt'] != null
          ? DateTime.parse(map['renewalRequestedAt'] as String)
          : null,
      terminationRequestedAt: map['terminationRequestedAt'] != null
          ? DateTime.parse(map['terminationRequestedAt'] as String)
          : null,
      paymentConfirmedAt: map['paymentConfirmedAt'] != null
          ? DateTime.parse(map['paymentConfirmedAt'] as String)
          : null,
      renewedAt: map['renewedAt'] != null ? DateTime.parse(map['renewedAt'] as String) : null,
      transferRequestedAt: map['transferRequestedAt'] != null
          ? DateTime.parse(map['transferRequestedAt'] as String)
          : null,
      terminatedBy: map['terminatedBy'] as String?,

      transferStatus: map['transferStatus'] as String?,
      transferToTenantId: map["transferToTenantId"] as String?,

      isRenewed: map['isRenewed'] as bool? ?? false,
      previousLeaseId: map['previousLeaseId'] as String?,
      renewalReason: map['renewalReason'] as String?,

      transferApprovedAt: map['transferApprovedAt'] != null
          ? DateTime.parse(map['transferApprovedAt'] as String)
          : null,
      transferApprovedBy: map['transferApprovedBy'],
    );
  }

  Map<String, dynamic> toMap() => {
    'id': id,
    'applicationId': applicationId,
    'unitId': unitId,
    'tenantId': tenantId,
    'landownerId': landownerId,
    'propertyId': propertyId,
    'managerId': managerId,
    'startDate': startDate.toIso8601String(),
    'endDate': endDate.toIso8601String(),
    'nextDueDate': nextDueDate?.toIso8601String(),
    'monthlyRent': monthlyRent,
    'fees': fees?.map((e) => e.toMap()).toList(),
    'monthlyRentEquivalent': monthlyRentEquivalent,
    'durationMonths': durationMonths,
    'status': status,
    'generatedLeasePdfUrl': generatedLeasePdfUrl,
    'customLeasePdfUrl': customLeasePdfUrl,
    'signedAgreementPdfUrl': signedAgreementPdfUrl,
    'isCustomLease': isCustomLease,
    'signedAt': signedAt?.toIso8601String(),
    'signedBy': signedBy,
    'termsNotes': termsNotes,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'terminationReason': terminationReason,
    'terminatedAt': terminatedAt?.toIso8601String(),
    'renewalRequestedAt': renewalRequestedAt?.toIso8601String(),
    'terminationRequestedAt': terminationRequestedAt?.toIso8601String(),
    'transferRequestedAt': transferRequestedAt?.toIso8601String(),
    'paymentConfirmedAt': paymentConfirmedAt?.toIso8601String(),
    'renewedAt': renewedAt?.toIso8601String(),
    'terminatedBy': terminatedBy,

    'transferToTenantId': transferToTenantId,
    'transferStatus': transferStatus,

    'isRenewed': isRenewed,
    'previousLeaseId': previousLeaseId,
    'renewalReason': renewalReason,

    'transferApprovedBy': transferApprovedBy,
    'transferApprovedAt': transferApprovedAt?.toIso8601String(),
  };

  LeaseModel copyWith({
    String? id,
    String? applicationId,
    String? unitId,
    String? tenantId,
    String? landownerId,
    String? propertyId,
    String? managerId,
    DateTime? startDate,
    DateTime? endDate,
    double? monthlyRentEquivalent,
    DateTime? nextDueDate,
    double? monthlyRent,
    int? durationMonths,
    String? status,
    String? generatedLeasePdfUrl,
    String? customLeasePdfUrl,
    String? signedAgreementPdfUrl,
    String? terminationReason,
    List<UnitFee>? fees,
    DateTime? terminatedAt,
    DateTime? renewalRequestedAt,
    DateTime? terminationRequestedAt,
    DateTime? transferRequestedAt,

    String? terminatedBy,
    String? transferStatus,
    String? transferToTenantId,
    bool? isCustomLease,
    DateTime? signedAt,
    String? signedBy,
    String? termsNotes,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? paymentConfirmedAt,
    DateTime? renewedAt,

    bool? isRenewed,
    String? previousLeaseId,
    String? renewalReason,

    DateTime? transferApprovedAt,

    String? transferApprovedBy,
  }) {
    return LeaseModel(
      id: id ?? this.id,
      applicationId: applicationId ?? this.applicationId,
      unitId: unitId ?? this.unitId,
      tenantId: tenantId ?? this.tenantId,
      landownerId: landownerId ?? this.landownerId,
      managerId: managerId ?? this.managerId,
      monthlyRentEquivalent: monthlyRentEquivalent ?? this.monthlyRentEquivalent,
      propertyId: propertyId ?? this.propertyId,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      nextDueDate: nextDueDate ?? this.nextDueDate,
      monthlyRent: monthlyRent ?? this.monthlyRent,
      fees: fees ?? this.fees,
      durationMonths: durationMonths ?? this.durationMonths,
      status: status ?? this.status,
      generatedLeasePdfUrl: generatedLeasePdfUrl ?? this.generatedLeasePdfUrl,
      customLeasePdfUrl: customLeasePdfUrl ?? this.customLeasePdfUrl,
      signedAgreementPdfUrl: signedAgreementPdfUrl ?? this.signedAgreementPdfUrl,
      isCustomLease: isCustomLease ?? this.isCustomLease,
      signedAt: signedAt ?? this.signedAt,
      signedBy: signedBy ?? this.signedBy,
      termsNotes: termsNotes ?? this.termsNotes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      terminationReason: terminationReason ?? this.terminationReason,
      terminatedAt: terminatedAt ?? this.terminatedAt,
      paymentConfirmedAt: paymentConfirmedAt ?? this.paymentConfirmedAt,
      renewedAt: renewedAt ?? this.renewedAt,
      renewalRequestedAt: renewalRequestedAt ?? this.renewalRequestedAt,
      terminationRequestedAt: terminationRequestedAt ?? this.terminationRequestedAt,
      transferRequestedAt: transferRequestedAt ?? this.transferRequestedAt,
      terminatedBy: terminatedBy ?? this.terminatedBy,
      transferStatus: transferStatus ?? this.transferStatus,
      transferToTenantId: transferToTenantId ?? this.transferToTenantId,
      isRenewed: isRenewed ?? this.isRenewed,
      previousLeaseId: previousLeaseId ?? this.previousLeaseId,
      renewalReason: renewalReason ?? this.renewalReason,

      transferApprovedAt: transferApprovedAt ?? this.transferApprovedAt,
      transferApprovedBy: transferApprovedBy ?? this.transferApprovedBy,
    );
  }
}
